# Generated by Django 5.2.5 on 2025-08-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlimage',
            name='image',
        ),
        migrations.AddField(
            model_name='urlimage',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
    ]
