# Generated by Django 5.2.3 on 2025-06-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100, unique=True)),
                ('dep_datail', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stuname', models.CharField(max_length=100)),
                ('Stuemail', models.EmailField(max_length=254)),
                ('Stucontact', models.IntegerField()),
                ('Stu_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_data', to='app11th.department', to_field='dep_name')),
            ],
        ),
    ]
