# Generated by Django 5.2.3 on 2025-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app9th', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='userid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empid',
            field=models.IntegerField(),
        ),
    ]
