# Generated by Django 5.2.3 on 2025-06-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app9th', '0002_alter_client_userid_alter_employee_empid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
