# Generated by Django 5.2.3 on 2025-06-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app9th', '0004_basedata_delete_client_delete_employee_employe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basedata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('branch', models.CharField()),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='basedata_ptr',
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app9th.basedata2',),
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.DeleteModel(
            name='Basedata',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
