# Generated by Django 5.2.3 on 2025-06-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10th', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='addhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_info', to='app10th.addhar', to_field='aadhar'),
        ),
    ]
