# Generated by Django 5.2.3 on 2025-06-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4th', '0002_rename_stu_city_student_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(),
        ),
    ]
