# Generated by Django 5.2.4 on 2025-07-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemdes', models.CharField()),
                ('itemprice', models.IntegerField()),
                ('itemimage', models.ImageField(upload_to='file')),
                ('itemcolor', models.CharField()),
            ],
        ),
    ]
