# Generated by Django 5.2.5 on 2025-08-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('city', models.CharField()),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
